on:
  schedule:
  - cron:  "* * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v3
      with:
        source_repo: "https://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@github.com/swamirajpatil1272/sam2.git"
        source_branch: "main"
        destination_branch: "new"
        github_token: ${{ secrets.PAT }}
